development:
  adapter: postgis
  postgis_extension: true
  host: 10.1.0.73
  port: 5432
  encoding: LATIN1
  #collate: en_US.UTF8
  #ctype: en_US.UTF8
  database: geoprefeitura
  pool: 5
  username: geo
  password: geo
  #schema_search_path: "public,postgis"
  script_dir: /usr/share/postgresql/9.1/contrib/postgis-1.5

production:
  adapter: postgis
  postgis_extension: true
  host: 10.1.0.73
  port: 5432
  encoding: LATIN1   #utf8
  #collate: en_US.UTF8
  #ctype: en_US.UTF8
  database: geoprefeitura
  pool: 5
  username: geo
  password: geo
  #schema_search_path: "public,postgis"
  script_dir: /usr/share/postgresql/9.1/contrib/postgis-1.5

# test:
#   adapter: postgis
#   encoding: UTF8
#   database: georails_test
#   pool: 5
#   username: geo
#   password: geo
#   schema_search_path: "public,postgis"
#   script_dir: /usr/share/postgresql/9.1/contrib/postgis-1.5